# These are supported funding model platforms

github: # Replace With Upto 4 (Separate Using ",") Github Sponsor Enabled Usernames: https://github.com/sponsors
patreon: # Replace With A Patreon Username: https://www.patreon.com/
open_collective: # Replace With A Open Collective Username (Minimum 100 stars): https://opencollective.com/
ko_fi: # Replace With A Ko-fi Username: http://ko-fi.com/
tidelift: # Replace With A Tidelift platform-name/package-name: https://tidelift.com/
community_bridge: # Replace With A Community Bridge Username: https://communitybridge.org/
liberapay: # Replace With A Liberapay Username: http://liberapay.com/
issuehunt: # Replace With A IssueHunt Username: https://issuehunt.io/
otechie: # Replace With A Otechie username: https://otechie.com/
custom: # Replace With Upto 4 ( Separate Using "," ) custom sponsorship URLs