blank_issues_enabled: true
contact_links:
  - name: Community Discussions
    url: https://github.com/krishdevdb/repo-template/discussions
    about: Repo Template Github Community Resides Here
  - name: Discord Server
    url: https://discord.gg/xqh38kb6sv
    about: Are You A Discord Person, We are too. Join us on discord
  - name: Twitter
    url: https://twitter.com/krishdevdb
    about: Official Twitter Of The Author